
//----------------------------------------------------------------------------------
// <autogenerated>
//		This code was generated by a tool.
//		Changes to this file may cause incorrect behaviour and will be lost 
//		if the code is regenerated.
// </autogenerated>
//----------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Globalization;
using Soneta.Types;
using Soneta.Business;
using enovaGitHubAnalyser;

[assembly: ModuleType("GitHub", typeof(enovaGitHubAnalyser.GitHubModule), 4, "GitHub", 1, VersionNumber=1)]

namespace enovaGitHubAnalyser {

	/// <summary>
	/// Moduł GitHub.
	/// </summary>
	/// <seealso cref="Soneta.Business.Module"/>
	/// <seealso cref="Soneta.Business.Session"/>
	[System.CodeDom.Compiler.GeneratedCode("Soneta.Generator", "4")]
	public partial class GitHubModule : Module {

		public static GitHubModule GetInstance(ISessionable session) => (GitHubModule)session?.Session?.Modules[moduleInfo];

		private static Soneta.Business.App.ModuleInfo moduleInfo = new Soneta.Business.App.ModuleInfo(session => new GitHubModule(session)) {
		};

		GitHubModule(Session session) : base(session) {}

		private static Soneta.Business.App.TableInfo tableInfoCommits = new Soneta.Business.App.TableInfo.Create<Commits, GitHubCommit, GitHubCommitRecord>("GitHubCo") {
		};

		public Commits Commits => (Commits)Session.Tables[tableInfoCommits];

		private static Soneta.Business.App.KeyInfo keyInfoGitHubCommitIdentyfikator = new Soneta.Business.App.KeyInfo(tableInfoCommits, table => new GitHubCommitTable.IdentyfikatorKey(table)) {
			Name = "Identyfikator",
			Unique = true,
			PrimaryKey = true,
			KeyFields = new[] {"Sha"},
		};

		/// <summary>
		/// Klasa implementująca standardową obsługę tabeli obiektów GitHubCommit.
		/// Dziedzicząca klasa <see cref="Commits"/> zawiera kod użytkownika
		/// zawierający specyficzną funkcjonalność tabeli, która nie zawiera się w funkcjonalności
		/// biblioteki <see cref="Soneta.Business"/>.
		/// </summary>
		/// <seealso cref="Commits"/>
		/// <seealso cref="GitHubCommitRow"/>
		/// <seealso cref="GitHubCommit"/>
		/// <seealso cref="Soneta.Business.Table"/>
		[Caption("Tabela z dodanymi comitty'ami")]
		public abstract partial class GitHubCommitTable : GuidedTable {

			protected GitHubCommitTable() {}

			public class IdentyfikatorKey : Key<GitHubCommit> {
				internal IdentyfikatorKey(Table table) : base(table) {
				}

				protected override object[] GetData(Row row, Record rec) => new object[] {
					((GitHubCommitRecord)rec).Sha.TrimEnd()
				};

				public GitHubCommit this[string sha] => (GitHubCommit)Find(sha);
			}

			public IdentyfikatorKey Identyfikator => (IdentyfikatorKey)Session.Keys[keyInfoGitHubCommitIdentyfikator];


			/// <summary>
			/// Typowane property dostarczające obiekt modułu zawierającegą tą tabelę. Umożliwia dostęp do
			/// innych obiektów znajdujących się w tym samym module.
			/// </summary>
			/// <seealso cref="GitHubModule"/>
			public new GitHubModule Module => (GitHubModule)base.Module;

			/// <summary>
			/// Typowany indekser dostarczający obiekty znajdujące się w tej tabeli przy pomocy 
			/// ID identyfikującego jednoznacznie obiekt w systemie.
			/// </summary>
			/// <param name="id">Liczba będąca unikalnym identyfikatorem obiektu. Wartości
			/// ujemne identyfikują obiekty, które zostały dodane i nie są jeszcze zapisane do bazy danych.</param>
			/// <seealso cref="GitHubCommit"/>
			public new GitHubCommit this[int id] => (GitHubCommit)base[id];

			/// <summary>
			/// Typowany indekser dostarczający obiekty znajdujące się w tej tabeli przy pomocy 
			/// tablicy ID identyfikujących jednoznacznie obiekt w systemie.
			/// </summary>
			/// <param name="id">Tablica liczb będąca unikalnymi identyfikatorami obiektu. Wartości
			/// ujemne identyfikują obiekty, które zostały dodane i nie są jeszcze zapisane do bazy danych.</param>
			/// <seealso cref="GitHubCommit"/>
			public new GitHubCommit[] this[int[] ids] => (GitHubCommit[])base[ids];

			public new GitHubCommit this[Guid guid] => (GitHubCommit)base[guid];

			protected override Row CreateRow(RowCreator creator) => new GitHubCommit();

			[Soneta.Langs.TranslateIgnore]
			protected override sealed void PrepareNames(StringBuilder names, string divider) {
				names.Append(divider); names.Append("Guid");
				names.Append(divider); names.Append("Sha");
				names.Append(divider); names.Append("Autor");
				names.Append(divider); names.Append("Data");
			}

		}

		public abstract partial class GitHubCommitRow : GuidedRow {

			private GitHubCommitRecord record;

			protected override void AssignRecord(Record rec) {
				record = (GitHubCommitRecord)rec;
			}

			protected GitHubCommitRow() : base(true) {
			}

			[MaxLength(255)]
			[Required]
			public string Sha {
				get {
					if (record==null) GetRecord();
					return record.Sha;
				}
				set {
					GitHubCommitSchema.ShaBeforeEdit?.Invoke((GitHubCommit)this, ref value);
					if (value!=null) value = value.TrimEnd();
					if (string.IsNullOrEmpty(value)) throw new RequiredException(this, "Sha");
					if (value.Length>ShaLength) throw new ValueToLongException(this, "Sha", ShaLength);
					GetEdit(record==null, false);
					record.Sha = value;
					if (State!=RowState.Detached) {
						ResyncSet(keyInfoGitHubCommitIdentyfikator);
					}
					GitHubCommitSchema.ShaAfterEdit?.Invoke((GitHubCommit)this);
				}
			}

			public const int ShaLength = 255;

			[MaxLength(100)]
			public string Autor {
				get {
					if (record==null) GetRecord();
					return record.Autor;
				}
				set {
					GitHubCommitSchema.AutorBeforeEdit?.Invoke((GitHubCommit)this, ref value);
					if (value!=null) value = value.TrimEnd();
					if (value.Length>AutorLength) throw new ValueToLongException(this, "Autor", AutorLength);
					GetEdit(record==null, false);
					record.Autor = value;
					GitHubCommitSchema.AutorAfterEdit?.Invoke((GitHubCommit)this);
				}
			}

			public const int AutorLength = 100;

			public Date Data {
				get {
					if (record==null) GetRecord();
					return record.Data;
				}
				set {
					GitHubCommitSchema.DataBeforeEdit?.Invoke((GitHubCommit)this, ref value);
					GetEdit(record==null, false);
					record.Data = value;
					GitHubCommitSchema.DataAfterEdit?.Invoke((GitHubCommit)this);
				}
			}

			[Browsable(false)]
			public new Commits Table => (Commits)base.Table;

			[Browsable(false)]
			public GitHubModule Module => Table.Module;

			protected override Soneta.Business.App.TableInfo TableInfo => tableInfoCommits;

			public sealed override AccessRights GetObjectRight() {
				AccessRights ar = CalcObjectRight();
				GitHubCommitSchema.OnCalcObjectRight?.Invoke((GitHubCommit)this, ref ar);
				return ar;
			}

			protected sealed override AccessRights GetParentsObjectRight() {
				AccessRights result = CalcParentsObjectRight();
				GitHubCommitSchema.OnCalcParentsObjectRight?.Invoke((GitHubCommit)this, ref result);
				return result;
			}

			protected override bool CalcReadOnly() {
				bool result = false;
				GitHubCommitSchema.OnCalcReadOnly?.Invoke((GitHubCommit)this, ref result);
				return result;
			}

			class ShaRequiredVerifier : RequiredVerifier {
				internal ShaRequiredVerifier(IRow row) : base(row, "Sha") {
				}
				protected override bool IsValid() => !(string.IsNullOrEmpty(((GitHubCommitRow)Row).Sha));
			}

			protected override void OnAdded() {
				base.OnAdded();
				Session.Verifiers.Add(new ShaRequiredVerifier(this));
				GitHubCommitSchema.OnAdded?.Invoke((GitHubCommit)this);
			}

			protected override void OnLoaded() {
				base.OnLoaded();
				GitHubCommitSchema.OnLoaded?.Invoke((GitHubCommit)this);
			}

			protected override void OnEditing() {
				base.OnEditing();
				GitHubCommitSchema.OnEditing?.Invoke((GitHubCommit)this);
			}

			protected override void OnDeleting() {
				base.OnDeleting();
				GitHubCommitSchema.OnDeleting?.Invoke((GitHubCommit)this);
			}

			protected override void OnDeleted() {
				base.OnDeleted();
				GitHubCommitSchema.OnDeleted?.Invoke((GitHubCommit)this);
			}

			protected override void OnRepacked() {
				base.OnRepacked();
				GitHubCommitSchema.OnRepacked?.Invoke((GitHubCommit)this);
			}

		}

		public sealed class GitHubCommitRecord : GuidedRecord {
			[Required]
			[MaxLength(255)]
			public string Sha = "";
			[MaxLength(100)]
			public string Autor = "";
			public Date Data;

			public override Record Clone() {
				GitHubCommitRecord rec = (GitHubCommitRecord)MemberwiseClone();
				return rec;
			}

			public override void Load(RecordReader creator) {
				Guid = creator.Read_guid();
				Sha = creator.Read_string();
				Autor = creator.Read_string();
				Data = creator.Read_date();
			}
		}

		public static class GitHubCommitSchema {

			internal static RowDelegate<GitHubCommitRow, string> ShaBeforeEdit;
			public static void AddShaBeforeEdit(RowDelegate<GitHubCommitRow, string> value)
				=> ShaBeforeEdit = (RowDelegate<GitHubCommitRow, string>)Delegate.Combine(ShaBeforeEdit, value);

			internal static RowDelegate<GitHubCommitRow> ShaAfterEdit;
			public static void AddShaAfterEdit(RowDelegate<GitHubCommitRow> value)
				=> ShaAfterEdit = (RowDelegate<GitHubCommitRow>)Delegate.Combine(ShaAfterEdit, value);

			internal static RowDelegate<GitHubCommitRow, string> AutorBeforeEdit;
			public static void AddAutorBeforeEdit(RowDelegate<GitHubCommitRow, string> value)
				=> AutorBeforeEdit = (RowDelegate<GitHubCommitRow, string>)Delegate.Combine(AutorBeforeEdit, value);

			internal static RowDelegate<GitHubCommitRow> AutorAfterEdit;
			public static void AddAutorAfterEdit(RowDelegate<GitHubCommitRow> value)
				=> AutorAfterEdit = (RowDelegate<GitHubCommitRow>)Delegate.Combine(AutorAfterEdit, value);

			internal static RowDelegate<GitHubCommitRow, Date> DataBeforeEdit;
			public static void AddDataBeforeEdit(RowDelegate<GitHubCommitRow, Date> value)
				=> DataBeforeEdit = (RowDelegate<GitHubCommitRow, Date>)Delegate.Combine(DataBeforeEdit, value);

			internal static RowDelegate<GitHubCommitRow> DataAfterEdit;
			public static void AddDataAfterEdit(RowDelegate<GitHubCommitRow> value)
				=> DataAfterEdit = (RowDelegate<GitHubCommitRow>)Delegate.Combine(DataAfterEdit, value);

			internal static RowDelegate<GitHubCommitRow> OnLoaded;
			public static void AddOnLoaded(RowDelegate<GitHubCommitRow> value)
				=> OnLoaded = (RowDelegate<GitHubCommitRow>)Delegate.Combine(OnLoaded, value);

			internal static RowDelegate<GitHubCommitRow> OnAdded;
			public static void AddOnAdded(RowDelegate<GitHubCommitRow> value)
				=> OnAdded = (RowDelegate<GitHubCommitRow>)Delegate.Combine(OnAdded, value);

			internal static RowDelegate<GitHubCommitRow> OnEditing;
			public static void AddOnEditing(RowDelegate<GitHubCommitRow> value)
				=> OnEditing = (RowDelegate<GitHubCommitRow>)Delegate.Combine(OnEditing, value);

			internal static RowDelegate<GitHubCommitRow> OnDeleting;
			public static void AddOnDeleting(RowDelegate<GitHubCommitRow> value)
				=> OnDeleting = (RowDelegate<GitHubCommitRow>)Delegate.Combine(OnDeleting, value);

			internal static RowDelegate<GitHubCommitRow> OnDeleted;
			public static void AddOnDeleted(RowDelegate<GitHubCommitRow> value)
				=> OnDeleted = (RowDelegate<GitHubCommitRow>)Delegate.Combine(OnDeleted, value);

			internal static RowDelegate<GitHubCommitRow> OnRepacked;
			public static void AddOnRepacked(RowDelegate<GitHubCommitRow> value)
				=> OnRepacked = (RowDelegate<GitHubCommitRow>)Delegate.Combine(OnRepacked, value);

			internal static RowAccessRightsDelegate<GitHubCommitRow> OnCalcObjectRight;
			public static void AddOnCalcObjectRight(RowAccessRightsDelegate<GitHubCommitRow> value)
				=> OnCalcObjectRight = (RowAccessRightsDelegate<GitHubCommitRow>)Delegate.Combine(OnCalcObjectRight, value);

			internal static RowAccessRightsDelegate<GitHubCommitRow> OnCalcParentsObjectRight;
			public static void AddOnCalcParentsObjectRight(RowAccessRightsDelegate<GitHubCommitRow> value)
				=> OnCalcParentsObjectRight = (RowAccessRightsDelegate<GitHubCommitRow>)Delegate.Combine(OnCalcParentsObjectRight, value);

			internal static RowReadOnlyDelegate<GitHubCommitRow> OnCalcReadOnly;
			public static void AddOnCalcReadOnly(RowReadOnlyDelegate<GitHubCommitRow> value)
				=> OnCalcReadOnly = (RowReadOnlyDelegate<GitHubCommitRow>)Delegate.Combine(OnCalcReadOnly, value);

		}

	}

	[System.CodeDom.Compiler.GeneratedCode("Soneta.Generator", "4")]
	public static class StaticsGitHubModule {
		public static GitHubModule GetGitHub(this Session session) => GitHubModule.GetInstance(session);
	}

}

